postgres_db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "csv_service"
  password: "gaga565"
  sslmode: "disable"

mongo_db:
  host: "localhost"
  port: "27017"
  dbname: "notify"
  usrs_collection: "users"